# Generated by Django 5.0.3 on 2024-04-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_desc_alter_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='category/'),
        ),
    ]
